### PR TITLE
Added As per syntax !

### PR DESCRIPTION
**Pull request by talktovik**
Thanks for your signature. Make sure the following rules are correctly followed.

* Please add your signature at the end of the list, at the bottom.
* Just one line, following the pattern you can see in the existing ones.
* Make sure the linked username in the signature matches exactly the GitHub handler of the account that opens the PR. This is the way to ensure the signature belongs to who has written the patch.

### CODE REVIEW

**Comment by brookmg** [comment]
It's not following the syntax.

**Comment by talktovik** [comment]
Enlighten me then :)

**Comment by brookmg** [comment]
`[title](https://www.example.com)` <- This is how you write a link on the markdown. In your case `Vikas Yadav ([@talktovik](https://talktovik.github.io/)), Software Engineer, India` should work fine. Close this PR and open a new one with a single commit only adding a signature at the bottom 👍

**Comment by talktovik** [comment]
Okay thanks !

**Pull request closed without merging**
