### PR TITLE
Fix mistakes in markdown grammar

### PR DESCRIPTION
**Pull request by teruteru128**

### CODE REVIEW

**Comment by fxn** [comment]
Bot.

**Comment by acid-chicken** [comment]
Hey @fxn,
He isn't a bot, is my friend. He wanna fix markdown errors. So, please see the file changes.
Thanks.

**Comment by fxn** [comment]
That account was just created, has no other activity, and adds angle brackets to URLs.

If the account is real, please tell your friend to rebase and revise the patch.

**Comment by teruteru128** [comment]
Deleting the angle brackets in the URL makes it difficult to accept because VSCode displays a warning ...

understood. I will accept.

**Comment by teruteru128** [comment]
PS.
Certainly I have not been action until now.
But My Account is Created In 2014!

**Comment by fxn** [comment]
OK, sorry for the confusion. There are a number of PRs that seem to be bots, or are meaningless (eg, they translate the README into some language, and the account does the same in two other projects and that is all its activity). This project has a lot of activity and those accounts waste my time. When I saw the angle brackets I suspected something automated.

Thanks for the edits, they are all good.

**Comment by teruteru128** [comment]
Excuse me, aren't you going to remove the "Waiting for" label?
Or, is it a policy not to remove labels?

**Comment by teruteru128** [comment]
Thanks.

**Comment by fxn** [comment]
Oh yes, thanks!

**Pull request merged**
