### PR TITLE
Remove myself from the signatures list

### PR DESCRIPTION
**Pull request by thomaskuntzz**
Please remove me from this list. Thanks!

### CODE REVIEW

**Comment by thomaskuntzz** [comment]
Hello? Please, any answer? :pray:

**Comment by brookmg** [comment]
Any reason why?

**Comment by thomaskuntzz** [comment]
Yes, I singed this years ago and I don’t want to endorse what’s being said in this letter anymore.

But I don’t really wish to elaborate, please just remove my signature :)

**Comment by brookmg** [comment]
Sure thing @thomaskuntzz.

**Comment by thomaskuntzz** [comment]
Thanks!

**Pull request merged**
