### PR TITLE
added signature @frapsoft

### PR DESCRIPTION
**Pull request by ellerbrock**

### CODE REVIEW

**Comment by fxn** [comment]
Hi! We only accept signatures whose linked handler matches the account that opens the PR.

**Comment by ellerbrock** [comment]
Hi fxn, the signature links back to my account or am i missing something?

**Comment by fxn** [comment]
The linked handler should be "@ellerbrock".

**Comment by ellerbrock** [comment]
ah ok i see. i thought the @ part is the twitter nick :) ok no prob, i change it ...

**Comment by ellerbrock** [comment]
ups had a bit a mess up, deleted the repo and made a new pr :) u can close this one ...

**Comment by fxn** [comment]
Awesome :).

**Comment by ellerbrock** [comment]
thx for closing and merging of the new pr. i wish you a awesome weekend! cheers

**Pull request closed without merging**
