### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by DafsCode**

### CODE REVIEW

**Comment by fxn** [comment]
Hey man!

The signature should follow the pattern you can see used in the README, in your case it could be something like

```markdown
Dafydd ([@DafsCode](https://github.com/DafsCode)) 13, CS student, UK
```

Would you mind updating the patch?

**Comment by DafsCode** [comment]
Apologies, I'm still figuring this out haha

**Comment by fxn** [comment]
No prob at all! One easy solution for you could be to close this PR, edit the README again with the revised format, and open a new PR with that. What do you think?

**Comment by DafsCode** [comment]
Done! Thanks. 😊

**Pull request closed without merging**
