### PR TITLE
add(me)

### PR DESCRIPTION
**Pull request by jkurz**
Signed-off-by: Josh Kurz <josh.kurz@turner.com>

### CODE REVIEW

**Comment by thank-you-github** [comment]
Could you please rebase?

**Comment by jkurz** [comment]
rebased

**Comment by thank-you-github** [comment]
Thanks!

**Comment by jkurz** [comment]
I can see major issues with merge conflicts on this, maybe you should get pepole to add a file with their name and then generate the README from all the files created. That way you dont always have a million merge conflicts.

**Pull request merged**
