### PR TITLE
New signature

### PR DESCRIPTION
**Pull request by Zhipeng-Chang**
Please read and remove:

Practically all PRs are non-mergeable because they conflict with each other, and
continually asking for rebases would be impractical.

Because of that, it is likely that your signature is added via a commit that
references and closes the PR, rather than a regular merge. I have a supervised
script that processes the patches and commits them individually, referencing
their origin PR for credit and authenticity. In such case, you'll see said
commit linked in the notification email and in the page of the PR itself.

### CODE REVIEW

**Comment by Rameshkumarpolavarapu** [comment]
- Polavarapu Ramesh Kumar ([@Rameshkumarpolavarapu] (https://github.com/Rameshkumarpolavarapu)) Android Developer, Hyderabad, India.

**Comment by Rameshkumarpolavarapu** [comment]
- Polavarapu Ramesh Kumar ([@Rameshkumarpolavarapu] (https://github.com/Rameshkumarpolavarapu)) Android Developer, Hyderabad, India.
- Kodi Madhava Rao ([@KodiMadhavaRao] (https://github.com/KodiMadhavarao)) Android Developer, Hyderabad, India.

**Comment by fxn** [comment]
@Rameshkumarpolavarapu in order to sign, you need to open a pull request. Check [the closed ones](https://github.com/thank-you-github/thank-you-github/pulls?q=is%3Apr+is%3Aclosed), and the [guidelines](https://github.com/thank-you-github/thank-you-github/blob/master/.github/CONTRIBUTING.md).

People can only add their signature, cannot sign for others (as seen in the guidelines).

**Comment by Rameshkumarpolavarapu** [comment]
- Polavarapu Ramesh Kumar ([@Rameshkumarpolavarapu] (https://github.com/Rameshkumarpolavarapu)) Android Developer, Hyderabad, India.

**Pull request closed without merging**
