### PR TITLE
adding my signature, taking jab at sourceforge...

### PR DESCRIPTION
**Pull request by tiernano**
you may want to remove the jab at sourceforge, but i think its valid...

### CODE REVIEW

**Comment by thank-you-github** [comment]
Would prefer this letter to be kept short and positive if you don't mind!

**Comment by tiernano** [comment]
i can remove the looking at you sourceforge part if you want... i think its valid that the ads and malware part says though...

**Comment by thank-you-github** [comment]
I would prefer to keep the message as it is, no need to refer to other stuff except for the motivational initial part. The letter does not even refer to the project this one is a reaction to.

Short and positive.

**Comment by thank-you-github** [comment]
Going through all PRs like crazy, closing this by now but please feel free to reopen if you want to sign with the current wording!

**Pull request closed without merging**
